version: '3.1'
services:
  app:
    build: .
    container_name: node-app
    env_file: .env
    ports:
      - 3000:${SERVER_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
